### ISSUE TITLE
Forge 1.18.2 support

### ISSUE THREAD

**Issue by Atten007** [TheEpicBlock/PolyMc#139] opened 2022-02-24 15:22 UTC
Hi folks,

I want to make a Minecraft: Citybuild server named "Atten City" that should run 24/7 on my Raspberry Pi 4B. On this server, I want to play with Mods, there's a very cool mod named "Ultimate Car", but this is only available for Forge and not for Fabric. Now to my question: Can you please add forge support for this reason asap when the full Minecraft 1.18.2 update is released?

Sincerely yours,
Mika Kreis 😊

**Comment by QPCrummer** [comment] 2022-02-24 16:01
I mean, this is a fabric mod that is entirely based on fabric. So making it work in forge is basically impossible. However it will probably be updated to 1.18.2 when it does release.

**Comment by MrRubberDucky** [comment] 2022-02-24 16:36
please port to 1.2.5

**Comment by TheEpicBlock** [comment] 2022-02-24 16:57
Duplicate of #91, I don't have the time to maintain a Forge port at this moment

**Closed by TheEpicBlock** 2022-02-24 16:57 UTC
