### ISSUE TITLE
Kick on hitting an item

### ISSUE THREAD

**Issue by CamperSamu** [TheEpicBlock/PolyMc#20] opened 2020-07-19 23:08 UTC
When hitting an item dropped on the ground, the server kicks you for "Player Camper_Samu tried to attack an invalid entity"
I'm not sure this is a PolyMC bug, but I strongly belive it.

I am using a self-builded version of PolyMC with no modification (to get custom blocks)

**Comment by TheEpicBlock** [comment] 2020-07-21 15:18
I could not reproduce this. Could you give a list of mods used?

**Comment by TheEpicBlock** [comment] 2020-07-27 19:08
I'm going to close this now. I couldn't reproduce your issue. If I had to guess it's some kind of item pickup mod where you can click on items to pick them up.

**Closed by TheEpicBlock** 2020-07-27 19:08 UTC
Labels: bug

**Comment by CamperSamu** [comment] 2020-07-31 01:38
I realized today it was a mod I forgot I installed, sorry for making you loose time... (and sorry for not replying, I completely forgot about this issue until today)
