### ISSUE TITLE
Exception in Server Tick Loop

### ISSUE THREAD

**Issue by Raikaru** [TheEpicBlock/PolyMc#76] opened 2021-02-13 01:19 UTC
[crash-2021-02-12_20.08.28-server.txt](https://github.com/TheEpicBlock/PolyMc/files/5974917/crash-2021-02-12_20.08.28-server.txt)

I presume it is due to a mod conflict, if needed I'll try dropping in mods on a test server till I can figure out which is causing this

**Comment by TheEpicBlock** [comment] 2021-02-13 17:31
This is certainly an interesting issue. I believe the offender here is CCA, which is trying to access the BlockEntityRenderer via reflection. Which doesn't exists as this is a server. This call seem to originate from a mixin to BlockEntity. 
How PolyMc causes CCA to do this I've got no clue.

**Comment by TheEpicBlock** [comment] 2021-02-13 18:01
It seems like [this](https://github.com/OnyxStudios/Cardinal-Components-API/blob/68078eeba381ecf6e4a72dd7eab7a0be175fdc3c/cardinal-components-block/src/main/java/dev/onyxstudios/cca/internal/block/StaticBlockComponentPlugin.java#L129) is the code where it tries to access a BER. This however seems to be part of a lambda that is put inside a map., so it's still unclear how the BER got there in the first place.
The mixin that triggers this all seems to [here](https://github.com/OnyxStudios/Cardinal-Components-API/blob/68078eeba381ecf6e4a72dd7eab7a0be175fdc3c/cardinal-components-block/src/main/java/dev/onyxstudios/cca/mixin/block/common/MixinBlockEntity.java#L72). Which seems to try and find the component linked to the BE. 

I think the lambda is defining a way to call the factory of the component. This component seems to be registered to a BER for some odd reason and it's screwing things up. The `agap.main.Machines.MachineBlockEntity` might be the cause here. But I've been unable to find which mod it comes from.

**Comment by TheEpicBlock** [comment] 2021-02-13 18:22
Could you please confirm if this happens without PolyMc installed?

**Comment by Raikaru** [comment] 2021-02-13 18:24
It doesn't happen with PolyMC installed. I believe the mod that causes the problem might be agape space mod?

**Comment by TheEpicBlock** [comment] 2021-02-13 18:37
I believe that mod may somehow cause the issue. Can you confirm that, without PolyMc, placing the crank or some other machine block doesn't cause this to show up again?
PolyMc virtually places all blocks in order to test their collisions.

**Comment by Raikaru** [comment] 2021-02-13 19:10
It's definitely that mod I think. I placed down the crank and ye it was broken

**Comment by Raikaru** [comment] 2021-02-13 19:16
https://pastebin.com/LaJmhyw3

I don't know if you care about this one since Botania is still in development I believe but I believe there is a conflict between Botania and this mod

**Comment by TheEpicBlock** [comment] 2021-02-13 19:21
> It's definitely that mod I think. I placed down the crank and yeah it was

Then PolyMc isn't related to this. This is some weird conflict between that mod and CCA.

> I don't know if you care about this one since Botania is still in development I believe but I believe there is a conflict between Botania and this mod causing the same error

This seems to be a different issue, but I'll have a look. Thanks for reporting ^^'

**Comment by TheEpicBlock** [comment] 2021-03-07 13:51
I believe this has been semi-fixed in #0f3fd50493566552c6ddd6b5bb856f1446da14b9 
PolyMc won't be able to handle this block, but at least it won't crash entirely.

**Closed by TheEpicBlock** 2021-03-07 13:51 UTC
Labels: bug
