### ISSUE TITLE
RandomlyAddingAnything: Materials incompatibility

### ISSUE THREAD

**Issue by CamperSamu** [TheEpicBlock/PolyMc#18] opened 2020-07-18 18:10 UTC
https://github.com/vampire-studios/Randomly-Adding-Anything-Materials/issues/7

**Comment by TheEpicBlock** [comment] 2020-07-18 18:17
Thx! I'm looking into this now. I've already got a suspicion as to why it isn't working

**Comment by TheEpicBlock** [comment] 2020-07-18 18:33
Okay, I found the issue. The problem is that PolyMc expects the files to be present in the mod jar. Under `assets/`. If I look correctly, you're using Artifice to generate resourcepacks on the fly. Which is why PolyMc can't find the files in the mod jar.

I'll look if Artifice compatibility is possible.

**Comment by TheEpicBlock** [comment] 2020-07-18 20:04
Unfortunatly the resourcepacks generated by Artifice are client-side only. I'll add a fix so you can generate the resourcepack in singleplayer, it's the best I can do unfortunately.

**Comment by CamperSamu** [comment] 2020-07-19 21:07
ok, thanks!

**Comment by TheEpicBlock** [comment] 2020-07-21 15:06
With 2.0.0 Artifice compatibility has been added. See [this](https://github.com/TheEpicBlock/PolyMc/wiki/ModCompat#artifice). I have looked into what would be needed to make RAA: materials work on a server. Unfortunately a lot of the helper functions in Artifice are marked as client-side only. Which would make it a lot of work to do.

**Closed by TheEpicBlock** 2020-07-21 15:06 UTC
